services:
  app:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - ENVIRONMENT=development
    ports:
      - "80:4000"
    tty: true
